#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}/.."
main=Pearl
for module in "$main"*/; do
    module=${module%/}
    printf "$module.."

    printf ' %d headers.\n' "$(
        cd "$module"; headers=0
        {
            define=${module^^} define=${define//-/_}

            # Check wether the user has enabled the module from the Pearl prefix file (allowing all other modules to see its availability).
            printf '#ifndef %s\n' "$define"
            printf '#error %s used but not enabled.  If you want to use this library, first enable it with PEARL_USE(%s) in your Pearl prefix file.\n' "$define" "$define"
            printf '#endif\n\n'

            # All modules depend on Pearl.h
            [[ -e "$module-Dependencies.h" ]] && \
                printf '#import "%s.h"\n' "$module-Dependencies"
            printf '#import "%s.h"\n' "$main"

            # Enumerate the module's headers.
            while read f; do
                (( headers++ ))
                printf '#import "%s"\n' "${f##*/}"
            done < <(find . -name private -prune -o '(' ! -name "$module.h" ! -name "$module-*.h" -name '*.h' -print ')')
        } > "$module".h
        echo "$headers")"
done
