#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}/.."
main=Pearl
for module in "$main"*/; do
    module=${module%/}
    printf "$module.."

    printf ' %d headers.\n' "$(
        cd "$module"; headers=0
        {
            define=${module^^} define=${define//-/_}
            printf '#define %s\n' "${define}"
            printf '#import "%s.h"\n' "$main"
            while read f; do
                (( headers++ ))
                printf '#import "%s"\n' "${f##*/}"
            done < <(find . ! -name "$module.h" -name '*.h')
        } > "$module".h
        echo "$headers")"
done
