#!/usr/bin/env bash
# This script should be in the 'Scripts' directory under the git repository's root.
cd "${BASH_SOURCE%/*}/.."
shopt -s extglob


# Custom migration.
## Nothing yet.


# Update our modules
git submodule sync
git submodule update


# Our modules may define a custom update script, if so, run it.
find !(Scripts)/ -name "${BASH_SOURCE##*/}" -exec {} \;


# Finally, for our modules that haven't got a custom update script, update them recursively.
git submodule update --recursive --rebase
